#!/usr/bin/env python3
"""Hosted disposable emulator only: packaged login, upgrade, Threads and restart.

No configured user account, existing adb target, arbitrary server or external credentials.
Only allowlisted sanitized observations/captures survive; raw app/server logs never do.
"""
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import time
import urllib.request
import xml.etree.ElementTree as ET

APP = 'io.element.android.x.debug'
BASE = 'http://127.0.0.1:18949'
ANDROID_BASE = 'http://10.0.2.2:18949'
OUT = Path('app-runtime-evidence')
RESULT = {'source_sha': os.environ.get('EXPECTED_SHA'), 'boundary': 'disposable API33 x86_64 full app; synthetic unencrypted account; no physical audio', 'checks': []}


def adb(*args, data=None):
    result = subprocess.run(['adb', *args], input=data, capture_output=True, timeout=120)
    if result.returncode:
        raise RuntimeError('ADB operation failed')
    return result.stdout


def control(path, data):
    request = urllib.request.Request(BASE + '/_fixture/' + path, data=json.dumps(data).encode(), headers={'Content-Type': 'application/json'})
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.load(response)


def nodes():
    adb('shell', 'uiautomator', 'dump', '/sdcard/candidate-ui.xml')
    blob = adb('exec-out', 'cat', '/sdcard/candidate-ui.xml')
    root = ET.fromstring(blob)
    return list(root.iter('node'))


def labels(rows):
    return {n.get('text', '') for n in rows} | {n.get('content-desc', '') for n in rows}


def tap(node):
    box = list(map(int, re.findall(r'\d+', node.get('bounds', ''))))
    assert len(box) == 4
    adb('shell', 'input', 'tap', str((box[0] + box[2]) // 2), str((box[1] + box[3]) // 2))


def click(rows, names):
    for name in names:
        matches = [n for n in rows if name in (n.get('text'), n.get('content-desc'), n.get('resource-id')) and n.get('enabled') != 'false']
        if matches:
            tap(matches[-1])
            return True
    return False


def fill(node, value):
    # Passwords generated by fixture are URL-safe and never logged.
    assert re.fullmatch(r'[A-Za-z0-9_:@./-]+', value)
    tap(node)
    adb('shell', 'input', 'keyevent', 'KEYCODE_MOVE_END')
    existing = node.get('text', '')
    assert len(existing) <= 256, 'Unexpectedly long editable fixture field'
    if existing:
        # Sequential keyevent SHIFT does not hold a modifier on Android. Delete
        # the observed field contents explicitly, without clipboard or logs.
        adb('shell', 'input', 'keyevent', *(['KEYCODE_DEL'] * len(existing)))
    adb('shell', 'input', 'text', value)


def capture(name, rows=None):
    rows = rows or nodes()
    # Do not publish screenshot when any editable field exists; avoids credential leaks.
    if any(n.get('class') == 'android.widget.EditText' for n in rows):
        return
    (OUT / (name + '.png')).write_bytes(adb('exec-out', 'screencap', '-p'))


def check(name, passed, detail=None):
    RESULT['checks'].append({'id': name, 'passed': bool(passed), 'detail': detail})
    (OUT / 'results.json').write_text(json.dumps(RESULT, indent=2) + '\n')
    if not passed:
        raise AssertionError(name)


def launch():
    adb('shell', 'am', 'force-stop', APP)
    adb('shell', 'monkey', '-p', APP, '-c', 'android.intent.category.LAUNCHER', '1')


def login(user):
    submitted = False
    server_entered = False
    for attempt in range(45):
        time.sleep(1)
        rows = nodes()
        text = labels(rows)
        if 'Chats' in text:
            check('password-ui-login', submitted)
            return
        fields = [n for n in rows if n.get('class') == 'android.widget.EditText']
        if len(fields) >= 2:
            assert server_entered, 'Never submit credentials to an unselected account provider'
            if not submitted:
                fill(fields[0], user['user_id'])
                fill(fields[1], user['password'])
                adb('shell', 'input', 'keyevent', 'KEYCODE_BACK')
                click(nodes(), ['login-continue', 'Continue'])
                submitted = True
                continue
        elif len(fields) == 1 and not submitted:
            if not server_entered:
                fill(fields[0], ANDROID_BASE)
                server_entered = True
                adb('shell', 'input', 'keyevent', 'KEYCODE_BACK')
            click(nodes(), ['Continue', 'Next'])
            continue
        if submitted:
            # Fresh disposable account only; defer analytics/recovery/notification onboarding.
            if click(rows, ['Not now', 'Skip', 'Later', 'No thanks', 'Skip for now', 'Continue', 'Allow', 'While using the app']):
                continue
        else:
            if click(rows, ['Change account provider', 'Other', 'Other server', 'Sign in manually', 'Sign in', 'Get started']):
                continue
        # Preserve only static labels; no fields, passwords or generated account identifiers.
        RESULT['last_static_labels'] = sorted(t for t in text if t and '@' not in t and len(t) < 180 and not any(n.get('text') == t for n in fields))
    capture('login-blocked')
    check('password-ui-login', False, 'UI did not reach Chats; sanitized static labels retained')


def main():
    assert os.environ.get('GITHUB_ACTIONS') == 'true', 'Hosted-only: never use a local or user device'
    assert re.fullmatch(r'[0-9a-f]{40}', RESULT['source_sha'] or '')
    assert adb('shell', 'getprop', 'ro.kernel.qemu').strip() == b'1'
    devices = adb('devices').decode().splitlines()
    assert sum('\tdevice' in d for d in devices) == 1
    OUT.mkdir(exist_ok=True)
    check('emulator-identity', True, {'api': adb('shell', 'getprop', 'ro.build.version.sdk').decode().strip(), 'abi': adb('shell', 'getprop', 'ro.product.cpu.abi').decode().strip()})
    server_log = tempfile.TemporaryFile()
    server = subprocess.Popen([str(Path(os.environ['RUNNER_TEMP']) / 'threads-synapse-venv/bin/python'), 'scripts/threads-native/fixture_server.py', '--evidence', str(OUT / 'server')], stdout=server_log, stderr=server_log)
    try:
        for _ in range(180):
            if server.poll() is not None:
                # Allowlist diagnostics only; raw server logs can contain tokens.
                server_log.seek(0)
                raw = server_log.read().decode(errors='replace')
                RESULT['fixture_startup'] = {
                    'returncode': server.returncode,
                    'port_busy': 'Address already in use' in raw,
                    'wrong_version': 'Wrong Synapse version' in raw,
                    'dependency_missing': 'ModuleNotFoundError' in raw,
                }
                raise RuntimeError('Disposable fixture process exited; sanitized diagnostics retained')
            try:
                control('audit', {})
                break
            except OSError:
                time.sleep(.5)
        else:
            raise RuntimeError('Fixture did not start')
        check('disposable-fixture-ready', True)
        fixture = control('new', {'root_count': 1})
        # Previous public universal supports x86_64; exact immutable bytes checked before use.
        old = Path(os.environ['RUNNER_TEMP']) / 'prior-universal.apk'
        url = 'https://github.com/mergebloom/element-x-android/releases/download/reasoning-26.09.1-r1-debug/elementx-reasoning-26.09.1-r1-universal-debug.apk'
        # Public immutable download only. Bound transient redirect/TLS resets without
        # disabling certificate validation, following non-HTTPS redirects or weakening the digest.
        fetch = subprocess.run([
            'curl', '--fail', '--location', '--retry', '2', '--retry-all-errors', '--retry-delay', '2',
            '--connect-timeout', '20', '--max-time', '240', '--proto', '=https', '--proto-redir', '=https',
            '--silent', '--show-error', '--output', str(old), url,
        ], capture_output=True, timeout=750)
        check('prior-immutable-apk-download', fetch.returncode == 0)
        with old.open('rb') as f:
            assert hashlib.file_digest(f, 'sha256').hexdigest() == 'b2c08f70ffc7ae9412ae8bb21be0390f05bcce6d1dc1eb7a9352ce00c3f04029'
        assert b'Success' in adb('install', str(old))
        launch()
        login(fixture['alice'])
        capture('prior-synthetic-chats')
        candidates = list(Path('app/build/outputs/apk/gplay/debug').glob('*-x86_64-debug.apk'))
        assert len(candidates) == 1
        before = adb('shell', 'run-as', APP, 'ls', 'files')
        assert b'Success' in adb('install', '-r', str(candidates[0]))
        launch()
        for _ in range(30):
            rows = nodes()
            if 'Threads' in labels(rows):
                break
            time.sleep(1)
        check('same-signer-session-upgrade', 'Threads' in labels(rows) and before == adb('shell', 'run-as', APP, 'ls', 'files'))
        capture('candidate-home', rows)
        before_audit = control('audit', {})['receipt_writes']
        assert click(rows, ['Threads'])
        for _ in range(30):
            rows = nodes()
            if 'Unread' in labels(rows) and 'Recent' in labels(rows):
                break
            time.sleep(1)
        check('visible-unread-recent', {'Unread', 'Recent'} <= labels(rows))
        capture('candidate-threads-unread', rows)
        assert click(rows, ['Recent'])
        capture('candidate-threads-recent')
        check('directory-browse-no-receipts', before_audit == control('audit', {})['receipt_writes'])
        launch()
        for _ in range(30):
            rows = nodes()
            if 'Threads' in labels(rows):
                break
            time.sleep(1)
        check('force-stop-relaunch-session', 'Threads' in labels(rows))
        capture('candidate-restarted', rows)
        RESULT['success'] = True
    except Exception as exc:
        RESULT['success'] = False
        RESULT['error_type'] = type(exc).__name__
        raise
    finally:
        server.terminate()
        try:
            server.wait(timeout=20)
        except subprocess.TimeoutExpired:
            server.kill()
            server.wait()
        server_log.close()
        (OUT / 'results.json').write_text(json.dumps(RESULT, indent=2) + '\n')


if __name__ == '__main__':
    main()
